# Generated by Django 4.1.7 on 2023-03-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canhoto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canhoto',
            name='codigo',
            field=models.IntegerField(default=False, unique=True),
        ),
    ]
