# Generated by Django 4.1.7 on 2023-03-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canhoto', '0002_alter_canhoto_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canhoto',
            name='situacao',
        ),
        migrations.AddField(
            model_name='canhoto',
            name='tipo',
            field=models.CharField(default=1, max_length=100, verbose_name='tipo'),
            preserve_default=False,
        ),
    ]
