# Generated by Django 4.1.7 on 2023-03-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canhoto', '0003_remove_canhoto_situacao_canhoto_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='canhoto',
            name='tipo',
        ),
    ]
