# Generated by Django 4.1.7 on 2023-03-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canhoto', '0005_canhoto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='canhoto',
            name='codigo',
            field=models.IntegerField(default=False, unique=True, verbose_name='código'),
        ),
    ]
